import { jsPDF } from 'jspdf';
import { PredictionOutput } from './predictionService';
import { EpidemicData, HealthAlert } from './healthAlertsService';
import { Festival } from './festivalService';

export interface ComprehensiveReportData {
  hospitalName: string;
  city: string;
  region: string;
  
  // Pollution data
  aqi: number;
  aqiLevel: string;
  aqiForecast?: number[];
  pm25?: number;
  pm10?: number;
  
  // Weather data
  temperature?: number;
  humidity?: number;
  weatherCondition?: string;
  
  // Festival data
  upcomingFestivals?: Festival[];
  currentFestival?: Festival | null;
  
  // Prediction data
  prediction: PredictionOutput;
  
  // Epidemic data
  epidemicActive: boolean;
  epidemicData?: EpidemicData[];
  healthAlerts?: HealthAlert[];
  stateWiseData?: Array<{
    state: string;
    cases: number;
    severity: 'low' | 'moderate' | 'high';
  }>;
  
  // Additional metadata
  generatedBy: string;
  generatedAt: string;
}

/**
 * Generate comprehensive hospital management PDF report with all modules
 */
export function generateComprehensivePDFReport(data: ComprehensiveReportData): void {
  const doc = new jsPDF();
  
  let yPosition = 20;
  const leftMargin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - 40;

  // Helper function to add text with auto-wrap
  const addText = (text: string, x: number, y: number, maxWidth?: number, fontSize?: number) => {
    if (fontSize) doc.setFontSize(fontSize);
    if (maxWidth) {
      const lines = doc.splitTextToSize(text, maxWidth);
      doc.text(lines, x, y);
      return lines.length * (fontSize || 12) * 0.4;
    } else {
      doc.text(text, x, y);
      return (fontSize || 12) * 0.4;
    }
  };

  // Check if we need a new page
  const checkNewPage = (requiredSpace: number = 40) => {
    if (yPosition > 270 - requiredSpace) {
      doc.addPage();
      yPosition = 20;
      return true;
    }
    return false;
  };

  // Header Section
  doc.setFillColor(0, 150, 136);
  doc.rect(0, 0, pageWidth, 45, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text('Bharat PulseLink', leftMargin, 20);
  
  doc.setFontSize(16);
  doc.text('Comprehensive Hospital Management Report', leftMargin, 32);
  
  yPosition = 55;
  doc.setTextColor(0, 0, 0);

  // Hospital Information
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Hospital Information', leftMargin, yPosition);
  yPosition += 10;
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Hospital: ${data.hospitalName}`, leftMargin, yPosition);
  yPosition += 7;
  doc.text(`Location: ${data.city}, ${data.region}`, leftMargin, yPosition);
  yPosition += 7;
  doc.text(`Report Generated: ${new Date(data.generatedAt).toLocaleString()}`, leftMargin, yPosition);
  yPosition += 7;
  doc.text(`Generated By: ${data.generatedBy}`, leftMargin, yPosition);
  yPosition += 12;

  // Draw separator line
  doc.setDrawColor(200, 200, 200);
  doc.line(leftMargin, yPosition, pageWidth - leftMargin, yPosition);
  yPosition += 10;

  // ============================================
  // POLLUTION MONITORING SECTION
  // ============================================
  checkNewPage();
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 150, 136);
  doc.text('Pollution Monitoring', leftMargin, yPosition);
  doc.setTextColor(0, 0, 0);
  yPosition += 10;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  
  // AQI Box
  doc.setFillColor(245, 245, 245);
  doc.roundedRect(leftMargin, yPosition, contentWidth / 2 - 5, 30, 3, 3, 'F');
  doc.text('Air Quality Index (AQI)', leftMargin + 5, yPosition + 7);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  const aqiColor = getAQIColor(data.aqi);
  doc.setTextColor(aqiColor.r, aqiColor.g, aqiColor.b);
  doc.text(`${data.aqi}`, leftMargin + 5, yPosition + 20);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(data.aqiLevel, leftMargin + 40, yPosition + 20);
  doc.setTextColor(0, 0, 0);

  // Weather Box
  if (data.temperature !== undefined) {
    doc.setFillColor(245, 245, 245);
    doc.roundedRect(leftMargin + contentWidth / 2 + 5, yPosition, contentWidth / 2 - 5, 30, 3, 3, 'F');
    doc.text('Weather Conditions', leftMargin + contentWidth / 2 + 10, yPosition + 7);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(58, 134, 255);
    doc.text(`${data.temperature}°C`, leftMargin + contentWidth / 2 + 10, yPosition + 20);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(`${data.humidity}% humidity`, leftMargin + contentWidth / 2 + 45, yPosition + 20);
    doc.setTextColor(0, 0, 0);
  }

  yPosition += 40;

  // Particulate Matter Details
  if (data.pm25 || data.pm10) {
    doc.setFontSize(10);
    doc.text(`PM2.5: ${data.pm25 || 'N/A'} µg/m³  |  PM10: ${data.pm10 || 'N/A'} µg/m³`, leftMargin, yPosition);
    yPosition += 10;
  }

  // Draw separator
  doc.setDrawColor(200, 200, 200);
  doc.line(leftMargin, yPosition, pageWidth - leftMargin, yPosition);
  yPosition += 10;

  // ============================================
  // FESTIVAL CALENDAR SECTION
  // ============================================
  checkNewPage(50);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 150, 136);
  doc.text('Festival Calendar & Impact', leftMargin, yPosition);
  doc.setTextColor(0, 0, 0);
  yPosition += 10;

  // Current Festival
  if (data.currentFestival) {
    doc.setFillColor(253, 230, 138);
    doc.roundedRect(leftMargin, yPosition, contentWidth, 20, 3, 3, 'F');
    doc.setFontSize(11);
    doc.text('Current Festival:', leftMargin + 5, yPosition + 8);
    doc.setFont('helvetica', 'bold');
    doc.text(`${data.currentFestival.name}`, leftMargin + 5, yPosition + 15);
    doc.setFont('helvetica', 'normal');
    doc.text(`Surge: ${data.currentFestival.surge}`, leftMargin + 80, yPosition + 15);
    yPosition += 28;
  }

  // Upcoming Festivals
  if (data.upcomingFestivals && data.upcomingFestivals.length > 0) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Upcoming Festivals (Next 30 Days):', leftMargin, yPosition);
    yPosition += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);

    data.upcomingFestivals.slice(0, 5).forEach((festival, idx) => {
      checkNewPage(15);
      const severityColor = festival.level === 'high' ? { r: 239, g: 68, b: 68 } : 
                           festival.level === 'moderate' ? { r: 234, g: 179, b: 8 } : 
                           { r: 34, g: 197, b: 94 };
      
      doc.setFillColor(severityColor.r, severityColor.g, severityColor.b);
      doc.circle(leftMargin + 3, yPosition + 2, 1.5, 'F');
      doc.setTextColor(0, 0, 0);
      doc.text(`${festival.name} - ${festival.date}`, leftMargin + 8, yPosition + 4);
      doc.text(`(${festival.surge} surge)`, leftMargin + 100, yPosition + 4);
      yPosition += 7;
    });
    yPosition += 5;
  }

  // Draw separator
  doc.setDrawColor(200, 200, 200);
  doc.line(leftMargin, yPosition, pageWidth - leftMargin, yPosition);
  yPosition += 10;

  // ============================================
  // EPIDEMIC TRACKER SECTION
  // ============================================
  checkNewPage(60);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 150, 136);
  doc.text('Epidemic Surveillance', leftMargin, yPosition);
  doc.setTextColor(0, 0, 0);
  yPosition += 10;

  // Epidemic Alert
  if (data.epidemicActive && data.epidemicData && data.epidemicData.length > 0) {
    // Top Active Diseases
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Active Disease Surveillance:', leftMargin, yPosition);
    yPosition += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);

    data.epidemicData.slice(0, 6).forEach((disease, idx) => {
      checkNewPage(25);
      
      // Disease box
      const boxColor = disease.alertLevel === 'high' ? { r: 254, g: 202, b: 202 } :
                      disease.alertLevel === 'moderate' ? { r: 254, g: 243, b: 199 } :
                      { r: 220, g: 252, b: 231 };
      doc.setFillColor(boxColor.r, boxColor.g, boxColor.b);
      doc.roundedRect(leftMargin, yPosition, contentWidth, 18, 2, 2, 'F');
      
      doc.setTextColor(0, 0, 0);
      doc.setFont('helvetica', 'bold');
      doc.text(disease.disease, leftMargin + 5, yPosition + 6);
      doc.setFont('helvetica', 'normal');
      doc.text(`${disease.cases.toLocaleString()} cases`, leftMargin + 5, yPosition + 12);
      doc.text(`${disease.region}`, leftMargin + 80, yPosition + 6);
      doc.text(`Trend: ${disease.trend} (${disease.weeklyChange})`, leftMargin + 80, yPosition + 12);
      
      yPosition += 22;
    });
  } else {
    doc.setFillColor(220, 252, 231);
    doc.roundedRect(leftMargin, yPosition, contentWidth, 15, 3, 3, 'F');
    doc.setFontSize(10);
    doc.text('No active epidemic alerts at this time.', leftMargin + 5, yPosition + 10);
    yPosition += 20;
  }

  yPosition += 5;

  // State-wise Heatmap Summary
  if (data.stateWiseData && data.stateWiseData.length > 0) {
    checkNewPage(50);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('State-Wise Disease Distribution (Top 5):', leftMargin, yPosition);
    yPosition += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);

    data.stateWiseData.slice(0, 5).forEach((state, idx) => {
      checkNewPage(10);
      const severityColor = state.severity === 'high' ? { r: 239, g: 68, b: 68 } : 
                           state.severity === 'moderate' ? { r: 234, g: 179, b: 8 } : 
                           { r: 34, g: 197, b: 94 };
      
      doc.setFillColor(severityColor.r, severityColor.g, severityColor.b);
      doc.circle(leftMargin + 3, yPosition + 2, 1.5, 'F');
      doc.setTextColor(0, 0, 0);
      doc.text(`${state.state}`, leftMargin + 8, yPosition + 4);
      doc.text(`${state.cases.toLocaleString()} cases`, leftMargin + 80, yPosition + 4);
      yPosition += 7;
    });
    yPosition += 5;
  }

  // Latest Health Alerts
  if (data.healthAlerts && data.healthAlerts.length > 0) {
    checkNewPage(40);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Latest Health Alerts (News API & WHO):', leftMargin, yPosition);
    yPosition += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);

    data.healthAlerts.slice(0, 3).forEach((alert, idx) => {
      checkNewPage(20);
      doc.setFont('helvetica', 'bold');
      doc.text(alert.title.substring(0, 80), leftMargin + 5, yPosition);
      yPosition += 5;
      doc.setFont('helvetica', 'normal');
      doc.text(alert.description.substring(0, 120), leftMargin + 5, yPosition, contentWidth - 10);
      yPosition += 5;
      doc.setTextColor(100, 100, 100);
      doc.text(`Source: ${alert.source} | ${alert.region}`, leftMargin + 5, yPosition);
      doc.setTextColor(0, 0, 0);
      yPosition += 10;
    });
  }

  // Draw separator
  doc.setDrawColor(200, 200, 200);
  doc.line(leftMargin, yPosition, pageWidth - leftMargin, yPosition);
  yPosition += 10;

  // ============================================
  // AI PREDICTION SECTION
  // ============================================
  checkNewPage(50);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 150, 136);
  doc.text('AI-Powered Predictions', leftMargin, yPosition);
  doc.setTextColor(0, 0, 0);
  yPosition += 10;

  // Prediction Cards
  const cardHeight = 35;
  const cardWidth = contentWidth / 3 - 3;

  // Predicted Patients Card
  doc.setFillColor(239, 246, 255);
  doc.roundedRect(leftMargin, yPosition, cardWidth, cardHeight, 3, 3, 'F');
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Predicted Patient Load', leftMargin + 5, yPosition + 8);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(58, 134, 255);
  doc.text(`${data.prediction.predictedPatients}`, leftMargin + 5, yPosition + 23);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`+${data.prediction.surgePrediction}% surge`, leftMargin + 5, yPosition + 31);
  doc.setTextColor(0, 0, 0);

  // Staff Required Card
  doc.setFillColor(243, 232, 255);
  doc.roundedRect(leftMargin + cardWidth + 3, yPosition, cardWidth, cardHeight, 3, 3, 'F');
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Additional Staff', leftMargin + cardWidth + 8, yPosition + 8);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(139, 92, 246);
  doc.text(`${data.prediction.staffNeeded}`, leftMargin + cardWidth + 8, yPosition + 23);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('staff members', leftMargin + cardWidth + 8, yPosition + 31);
  doc.setTextColor(0, 0, 0);

  // Alert Level Card
  const alertColor = getAlertColor(data.prediction.alertLevel);
  doc.setFillColor(alertColor.bg.r, alertColor.bg.g, alertColor.bg.b);
  doc.roundedRect(leftMargin + 2 * (cardWidth + 3), yPosition, cardWidth, cardHeight, 3, 3, 'F');
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Alert Level', leftMargin + 2 * (cardWidth + 3) + 5, yPosition + 8);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(alertColor.text.r, alertColor.text.g, alertColor.text.b);
  doc.text(data.prediction.alertLevel.toUpperCase(), leftMargin + 2 * (cardWidth + 3) + 5, yPosition + 25);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');

  yPosition += cardHeight + 12;

  // Surge Breakdown
  checkNewPage();
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Surge Breakdown', leftMargin, yPosition);
  yPosition += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  const breakdown = [
    { label: 'Baseline Patients:', value: data.prediction.breakdown.baselinePatients },
    { label: 'Pollution Impact:', value: `+${data.prediction.breakdown.pollutionImpact}` },
    { label: 'Festival Impact:', value: `+${data.prediction.breakdown.festivalImpact}` },
    { label: 'Epidemic Impact:', value: `+${data.prediction.breakdown.epidemicImpact}` },
  ];

  breakdown.forEach((item) => {
    doc.text(item.label, leftMargin + 5, yPosition);
    doc.setFont('helvetica', 'bold');
    doc.text(`${item.value}`, leftMargin + 80, yPosition);
    doc.setFont('helvetica', 'normal');
    yPosition += 6;
  });

  yPosition += 10;

  // Recommendations Section
  checkNewPage();
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('AI Recommendations', leftMargin, yPosition);
  yPosition += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  data.prediction.recommendations.forEach((rec, index) => {
    checkNewPage(15);
    const bullet = `${index + 1}.`;
    doc.text(bullet, leftMargin, yPosition);
    const height = addText(rec, leftMargin + 10, yPosition, contentWidth - 10, 10);
    yPosition += Math.max(6, height + 2);
  });

  yPosition += 10;

  // Advisory Section
  checkNewPage(50);
  doc.setFillColor(236, 254, 255);
  doc.roundedRect(leftMargin, yPosition, contentWidth, 50, 3, 3, 'F');
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Advisory', leftMargin + 5, yPosition + 8);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  
  const cleanAdvisory = data.prediction.advisory
    .replace(/\*\*/g, '')
    .replace(/⚕️|📊|👥|🌫️|🎆|⚠️|🚨|⚡|✅/g, '')
    .trim();
  
  const advisoryLines = doc.splitTextToSize(cleanAdvisory.substring(0, 400), contentWidth - 10);
  doc.text(advisoryLines.slice(0, 5), leftMargin + 5, yPosition + 16);

  yPosition += 60;

  // Footer on every page
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    const footerY = doc.internal.pageSize.getHeight() - 20;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Bharat PulseLink — Comprehensive Hospital Intelligence Report', leftMargin, footerY);
    doc.text(`Report ID: ${Date.now()}`, pageWidth - leftMargin - 50, footerY);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth / 2 - 15, footerY);
  }

  // Save the PDF
  const filename = `BharatPulseLink_Comprehensive_Report_${data.city}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}

/**
 * Get color based on AQI level
 */
function getAQIColor(aqi: number): { r: number; g: number; b: number } {
  if (aqi <= 50) return { r: 34, g: 197, b: 94 };
  if (aqi <= 100) return { r: 250, g: 204, b: 21 };
  if (aqi <= 150) return { r: 251, g: 191, b: 36 };
  if (aqi <= 200) return { r: 249, g: 115, b: 22 };
  if (aqi <= 300) return { r: 239, g: 68, b: 68 };
  return { r: 139, g: 92, b: 246 };
}

/**
 * Get color based on alert level
 */
function getAlertColor(level: string): {
  bg: { r: number; g: number; b: number };
  text: { r: number; g: number; b: number };
} {
  switch (level) {
    case 'critical':
      return {
        bg: { r: 254, g: 202, b: 202 },
        text: { r: 185, g: 28, b: 28 },
      };
    case 'high':
      return {
        bg: { r: 254, g: 215, b: 170 },
        text: { r: 234, g: 88, b: 12 },
      };
    case 'moderate':
      return {
        bg: { r: 254, g: 249, b: 195 },
        text: { r: 161, g: 98, b: 7 },
      };
    case 'low':
      return {
        bg: { r: 220, g: 252, b: 231 },
        text: { r: 21, g: 128, b: 61 },
      };
    default:
      return {
        bg: { r: 243, g: 244, b: 246 },
        text: { r: 75, g: 85, b: 99 },
      };
  }
}

/* updated */
