import { jsPDF } from 'jspdf';
import { PredictionOutput } from './predictionService';

export interface ReportData {
  hospitalName: string;
  city: string;
  region: string;

  // Pollution data
  aqi: number;
  aqiLevel: string;
  aqiForecast?: number[];

  // Weather data
  temperature?: number;
  humidity?: number;
  weatherCondition?: string;

  // Festival data
  festivalName?: string | null;
  festivalDate?: string;
  festivalImpact?: string;

  // Prediction data
  prediction: PredictionOutput;

  // Epidemic data
  epidemicActive: boolean;
  epidemicName?: string;
  epidemicCases?: number;

  // Additional metadata
  generatedBy: string;
  generatedAt: string;
}

/**
 * Generate comprehensive hospital management PDF report
 */
export function generatePDFReport(data: ReportData): void {
  const doc = new jsPDF();

  let yPosition = 20;
  const leftMargin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - 40;

  // Helper function to add text with auto-wrap
  const addText = (text: string, x: number, y: number, maxWidth?: number, fontSize?: number) => {
    if (fontSize) doc.setFontSize(fontSize);
    if (maxWidth) {
      const lines = doc.splitTextToSize(text, maxWidth);
      doc.text(lines, x, y);
      return lines.length * (fontSize || 12) * 0.4; // Return height used
    } else {
      doc.text(text, x, y);
      return (fontSize || 12) * 0.4;
    }
  };

  // Header Section
  doc.setFillColor(0, 150, 136); // Teal color
  doc.rect(0, 0, pageWidth, 45, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text('Bharat PulseLink', leftMargin, 20);

  doc.setFontSize(16);
  doc.text('Predictive Hospital Management Report', leftMargin, 32);

  yPosition = 55;
  doc.setTextColor(0, 0, 0);

  // Hospital Information
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.text('Hospital Information', leftMargin, yPosition);
  yPosition += 10;

  doc.setFontSize(11);
  doc.setFont(undefined, 'normal');
  doc.text(`Hospital: ${data.hospitalName}`, leftMargin, yPosition);
  yPosition += 7;
  doc.text(`Location: ${data.city}, ${data.region}`, leftMargin, yPosition);
  yPosition += 7;
  doc.text(`Report Generated: ${new Date(data.generatedAt).toLocaleString()}`, leftMargin, yPosition);
  yPosition += 7;
  doc.text(`Generated By: ${data.generatedBy}`, leftMargin, yPosition);
  yPosition += 12;

  // Draw separator line
  doc.setDrawColor(200, 200, 200);
  doc.line(leftMargin, yPosition, pageWidth - leftMargin, yPosition);
  yPosition += 10;

  // Environmental Conditions Section
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(0, 150, 136);
  doc.text('Environmental Conditions', leftMargin, yPosition);
  doc.setTextColor(0, 0, 0);
  yPosition += 10;

  doc.setFontSize(11);
  doc.setFont(undefined, 'normal');

  // AQI Box
  doc.setFillColor(245, 245, 245);
  doc.roundedRect(leftMargin, yPosition, contentWidth / 2 - 5, 25, 3, 3, 'F');
  doc.text('Air Quality Index (AQI)', leftMargin + 5, yPosition + 7);
  doc.setFontSize(20);
  doc.setFont(undefined, 'bold');
  const aqiColor = getAQIColor(data.aqi);
  doc.setTextColor(aqiColor.r, aqiColor.g, aqiColor.b);
  doc.text(`${data.aqi}`, leftMargin + 5, yPosition + 18);
  doc.setFontSize(11);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(data.aqiLevel, leftMargin + 35, yPosition + 18);
  doc.setTextColor(0, 0, 0);

  // Weather Box
  if (data.temperature !== undefined) {
    doc.setFillColor(245, 245, 245);
    doc.roundedRect(leftMargin + contentWidth / 2 + 5, yPosition, contentWidth / 2 - 5, 25, 3, 3, 'F');
    doc.text('Weather Conditions', leftMargin + contentWidth / 2 + 10, yPosition + 7);
    doc.setFontSize(20);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(58, 134, 255);
    doc.text(`${data.temperature}°C`, leftMargin + contentWidth / 2 + 10, yPosition + 18);
    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(`Humidity: ${data.humidity}%`, leftMargin + contentWidth / 2 + 45, yPosition + 18);
    doc.setTextColor(0, 0, 0);
  }

  yPosition += 35;

  // Festival Information
  if (data.festivalName) {
    doc.setFillColor(253, 230, 138);
    doc.roundedRect(leftMargin, yPosition, contentWidth, 20, 3, 3, 'F');
    doc.setFontSize(11);
    doc.text('🎉 Festival Period:', leftMargin + 5, yPosition + 8);
    doc.setFont(undefined, 'bold');
    doc.text(`${data.festivalName}`, leftMargin + 5, yPosition + 15);
    doc.setFont(undefined, 'normal');
    doc.text(`Impact: ${data.festivalImpact || 'High'}`, leftMargin + 80, yPosition + 15);
    yPosition += 28;
  }

  // Epidemic Alert
  if (data.epidemicActive) {
    doc.setFillColor(254, 202, 202);
    doc.roundedRect(leftMargin, yPosition, contentWidth, 20, 3, 3, 'F');
    doc.setFontSize(11);
    doc.text('⚠️ Epidemic Alert:', leftMargin + 5, yPosition + 8);
    doc.setFont(undefined, 'bold');
    doc.text(`${data.epidemicName || 'Active Outbreak'}`, leftMargin + 5, yPosition + 15);
    doc.setFont(undefined, 'normal');
    doc.text(`Cases: ${data.epidemicCases || 'N/A'}`, leftMargin + 80, yPosition + 15);
    yPosition += 28;
  }

  // Draw separator
  doc.setDrawColor(200, 200, 200);
  doc.line(leftMargin, yPosition, pageWidth - leftMargin, yPosition);
  yPosition += 10;

  // AI Prediction Section
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(0, 150, 136);
  doc.text('AI-Powered Predictions', leftMargin, yPosition);
  doc.setTextColor(0, 0, 0);
  yPosition += 10;

  // Prediction Cards
  const cardHeight = 35;
  const cardWidth = contentWidth / 3 - 3;

  // Predicted Patients Card
  doc.setFillColor(239, 246, 255);
  doc.roundedRect(leftMargin, yPosition, cardWidth, cardHeight, 3, 3, 'F');
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Predicted Patient Load', leftMargin + 5, yPosition + 8);
  doc.setFontSize(24);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(58, 134, 255);
  doc.text(`${data.prediction.predictedPatients}`, leftMargin + 5, yPosition + 23);
  doc.setFontSize(9);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`+${data.prediction.surgePrediction}% surge`, leftMargin + 5, yPosition + 31);
  doc.setTextColor(0, 0, 0);

  // Staff Required Card
  doc.setFillColor(243, 232, 255);
  doc.roundedRect(leftMargin + cardWidth + 3, yPosition, cardWidth, cardHeight, 3, 3, 'F');
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Additional Staff Required', leftMargin + cardWidth + 8, yPosition + 8);
  doc.setFontSize(24);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(139, 92, 246);
  doc.text(`${data.prediction.staffNeeded}`, leftMargin + cardWidth + 8, yPosition + 23);
  doc.setFontSize(9);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('staff members', leftMargin + cardWidth + 8, yPosition + 31);
  doc.setTextColor(0, 0, 0);

  // Alert Level Card
  const alertColor = getAlertColor(data.prediction.alertLevel);
  doc.setFillColor(alertColor.bg.r, alertColor.bg.g, alertColor.bg.b);
  doc.roundedRect(leftMargin + 2 * (cardWidth + 3), yPosition, cardWidth, cardHeight, 3, 3, 'F');
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Alert Level', leftMargin + 2 * (cardWidth + 3) + 5, yPosition + 8);
  doc.setFontSize(18);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(alertColor.text.r, alertColor.text.g, alertColor.text.b);
  doc.text(data.prediction.alertLevel.toUpperCase(), leftMargin + 2 * (cardWidth + 3) + 5, yPosition + 25);
  doc.setTextColor(0, 0, 0);
  doc.setFont(undefined, 'normal');

  yPosition += cardHeight + 12;

  // Surge Breakdown
  doc.setFontSize(12);
  doc.setFont(undefined, 'bold');
  doc.text('Surge Breakdown', leftMargin, yPosition);
  yPosition += 8;

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');

  const breakdown = [
    { label: 'Baseline Patients:', value: data.prediction.breakdown.baselinePatients },
    { label: 'Pollution Impact:', value: `+${data.prediction.breakdown.pollutionImpact}` },
    { label: 'Festival Impact:', value: `+${data.prediction.breakdown.festivalImpact}` },
    { label: 'Epidemic Impact:', value: `+${data.prediction.breakdown.epidemicImpact}` },
  ];

  breakdown.forEach((item) => {
    doc.text(item.label, leftMargin + 5, yPosition);
    doc.setFont(undefined, 'bold');
    doc.text(`${item.value}`, leftMargin + 80, yPosition);
    doc.setFont(undefined, 'normal');
    yPosition += 6;
  });

  yPosition += 10;

  // Recommendations Section
  if (yPosition > 240) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(0, 150, 136);
  doc.text('AI Recommendations', leftMargin, yPosition);
  doc.setTextColor(0, 0, 0);
  yPosition += 10;

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');

  data.prediction.recommendations.forEach((rec, index) => {
    if (yPosition > 270) {
      doc.addPage();
      yPosition = 20;
    }

    const bullet = `${index + 1}.`;
    doc.text(bullet, leftMargin, yPosition);
    const height = addText(rec, leftMargin + 10, yPosition, contentWidth - 10, 10);
    yPosition += Math.max(6, height + 2);
  });

  yPosition += 10;

  // Advisory Section
  if (yPosition > 240) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setFillColor(236, 254, 255);
  doc.roundedRect(leftMargin, yPosition, contentWidth, 50, 3, 3, 'F');
  doc.setFontSize(12);
  doc.setFont(undefined, 'bold');
  doc.text('Executive Advisory', leftMargin + 5, yPosition + 8);
  doc.setFontSize(9);
  doc.setFont(undefined, 'normal');

  // Clean advisory text (remove markdown)
  const cleanAdvisory = data.prediction.advisory
    .replace(/\*\*/g, '')
    .replace(/⚕️|📊|👥|🌫️|🎆|⚠️|🚨|⚡|✅/g, '')
    .trim();

  const advisoryLines = doc.splitTextToSize(cleanAdvisory.substring(0, 400), contentWidth - 10);
  doc.text(advisoryLines.slice(0, 5), leftMargin + 5, yPosition + 16);

  yPosition += 60;

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 20;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Bharat PulseLink — Connecting Every Pulse to Better Health', leftMargin, footerY);
  doc.text(`Report ID: ${Date.now()}`, pageWidth - leftMargin - 50, footerY);
  doc.text(`Page 1 of ${doc.internal.pages.length - 1}`, pageWidth / 2 - 15, footerY);

  // Save the PDF
  const filename = `BharatPulseLink_Report_${data.city}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}

/**
 * Get color based on AQI level
 */
function getAQIColor(aqi: number): { r: number; g: number; b: number } {
  if (aqi <= 50) return { r: 34, g: 197, b: 94 }; // Green
  if (aqi <= 100) return { r: 250, g: 204, b: 21 }; // Yellow
  if (aqi <= 150) return { r: 251, g: 191, b: 36 }; // Light orange
  if (aqi <= 200) return { r: 249, g: 115, b: 22 }; // Orange
  if (aqi <= 300) return { r: 239, g: 68, b: 68 }; // Red
  return { r: 139, g: 92, b: 246 }; // Purple
}

/**
 * Get color based on alert level
 */
function getAlertColor(level: string): {
  bg: { r: number; g: number; b: number };
  text: { r: number; g: number; b: number };
} {
  switch (level) {
    case 'critical':
      return {
        bg: { r: 254, g: 202, b: 202 },
        text: { r: 185, g: 28, b: 28 },
      };
    case 'high':
      return {
        bg: { r: 254, g: 215, b: 170 },
        text: { r: 234, g: 88, b: 12 },
      };
    case 'moderate':
      return {
        bg: { r: 254, g: 249, b: 195 },
        text: { r: 161, g: 98, b: 7 },
      };
    case 'low':
      return {
        bg: { r: 220, g: 252, b: 231 },
        text: { r: 21, g: 128, b: 61 },
      };
    default:
      return {
        bg: { r: 243, g: 244, b: 246 },
        text: { r: 75, g: 85, b: 99 },
      };
  }
}

/**
 * Quick report generation with default data (for testing)
 */
export async function generateQuickReport(city: string = 'Chennai'): Promise<void> {
  // This would normally fetch real data from your services
  const mockData: ReportData = {
    hospitalName: 'Bharat PulseLink Hospital',
    city: city,
    region: 'Chennai',
    aqi: 218,
    aqiLevel: 'Poor',
    temperature: 29,
    humidity: 45,
    weatherCondition: 'Hazy',
    festivalName: 'Diwali',
    festivalDate: 'Nov 8, 2026',
    festivalImpact: 'High',
    epidemicActive: true,
    epidemicName: 'Dengue',
    epidemicCases: 1284,
    prediction: {
      predictedPatients: 520,
      staffNeeded: 68,
      surgePrediction: 42,
      alertLevel: 'high',
      advisory: 'Significant patient surge expected due to Diwali festival and high pollution levels.',
      recommendations: [
        'Deploy 16 additional nurses and 4 doctors',
        'Stock up on respiratory medicines and oxygen cylinders',
        'Prepare 20 extra beds in emergency ward',
        'Setup air purifiers in patient areas',
        'Brief staff on festival-related trauma protocols',
        'Ensure adequate burn treatment supplies',
      ],
      breakdown: {
        baselinePatients: 420,
        pollutionImpact: 42,
        festivalImpact: 50,
        epidemicImpact: 8,
      },
      timestamp: new Date().toISOString(),
    },
    generatedBy: 'Bharat PulseLink System',
    generatedAt: new Date().toISOString(),
  };

  generatePDFReport(mockData);
}

/* updated */
